window:

  startup_mode: Maximized

  padding:
    x: 10
    y: 10

  decorations: none
  opacity: 0.9

  dimensions:
    columns: 1536
    lines: 864

font:
  normal:
    family: agave Nerd Font
  size: 20

cursor:
  style:
    shape: Underline

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach 2>/dev/null || tmux"
env:
  TERM: xterm-256color

import:
  - ~/Dotfiles/alacritty/theme.yml

key_bindings:
  - { key: V, mods: Control, action: Paste }

