
window:
  padding:
    x: 0
    y: 10

  #     - full: Borders and title bar
  decorations: none

font:
  normal:
    family: MesloLGS NF

cursor:
  style:
    shape: Underline

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - "tmux attach || tmux"

colors:
  primary:
    background: '0x24283b'
    #foreground: '0x000000'
